# Generated by Django 3.2.9 on 2022-01-06 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('SecondName', models.CharField(max_length=50)),
                ('PatronymicName', models.CharField(blank=True, max_length=50)),
                ('BirthDate', models.DateField()),
            ],
        ),
    ]
